### ISSUE TITLE
app.add_device_name('BluezeroLight') fails

### ISSUE THREAD

**Issue by WayneKeenan** [ukBaz/python-bluezero#85]
Traceback (most recent call last):
  File "/home/pi/pycharm.projects/bluezero/examples/level10/light_switch.py", line 99, in <module>
    app.add_device_name('BluezeroLight')
  File "/home/pi/pycharm.projects/bluezero/bluezero/peripheral.py", line 183, in add_device_name
    self.dongle.alias(device_name)
TypeError: 'dbus.String' object is not callable

**Comment by ukBaz** [comment]
Thanks Wayne.

These two files are out of date as they use the version of the API from 0.0.1 and not the current 0.0.2.
The work we are doing elsewhere on Peripherals should end up replacing these files.

If you want to change the device name the format will now be:
```
self.dongle.alias = device_name
```

**Comment by ukBaz** [comment]
fixed by d1be4f9b015eace6a196b12b63e6878f4d921bf1
